<?xml version="1.0" encoding="UTF-8"?>
<project name="Calculator" default="compile" basedir=".">
    <description>Build file for Calculator Application</description>
    
    <property name="src" location="."/>
    <property name="build" location="build"/>
    <property name="dist" location="dist"/>
    <property name="lib" location="lib"/>
    
    <target name="init">
        <mkdir dir="${build}"/>
        <mkdir dir="${dist}"/>
        <mkdir dir="${lib}"/>
    </target>
    
    <target name="download-junit" depends="init">
        <get src="https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar" 
             dest="${lib}/junit-4.13.2.jar" 
             usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" 
             dest="${lib}/hamcrest-core-1.3.jar" 
             usetimestamp="true"/>
    </target>
    
    <target name="compile" depends="init">
        <javac srcdir="${src}" destdir="${build}" includeantruntime="false">
            <classpath>
                <fileset dir="${lib}" includes="*.jar"/>
            </classpath>
        </javac>
    </target>
    
    <target name="test" depends="compile, download-junit">
        <junit printsummary="yes" haltonfailure="yes">
            <classpath>
                <pathelement location="${build}"/>
                <fileset dir="${lib}" includes="*.jar"/>
            </classpath>
            <formatter type="brief" usefile="false"/>
            <test name="CalculatorLogicTest"/>
        </junit>
    </target>
    
    <target name="run" depends="compile">
        <java classname="Calculator" fork="true">
            <classpath>
                <pathelement location="${build}"/>
            </classpath>
        </java>
    </target>
    
    <target name="jar" depends="compile">
        <jar destfile="${dist}/Calculator.jar" basedir="${build}">
            <manifest>
                <attribute name="Main-Class" value="Calculator"/>
            </manifest>
        </jar>
    </target>
    
    <target name="clean">
        <delete dir="${build}"/>
        <delete dir="${dist}"/>
    </target>
</project>
