---
- name: Deploy Calculator App with Docker
  hosts: webservers

  tasks:
    - name: Pull the latest Docker image
      shell: docker pull aayanksinghai/scientific-calculator:latest
      register: pull_result

    - name: Stop and remove existing container
      shell: docker rm -f scientific-calculator
      ignore_errors: true

    - name: Run calculator container (detached)
      shell: docker run -d -p 8081:8080 --name scientific-calculator --restart unless-stopped aayanksinghai/scientific-calculator:latest
      register: container_output

    - name: Display container status
      shell: docker ps -f "name=scientific-calculator"
      register: container_status